### ISSUE TITLE
What is the purpose ot enabling "noexp" in certain situations?

### ISSUE THREAD

**Issue by alienbogart** [AardCrowley/Search-and-Destroy#111]
As a beginner, I'm really not sure what is the reasoning behind it.

**Comment by AardCrowley** [comment]
Noexp is useful for campaign leveling. Without the use of campaign reset tokens, you can only take a campaign once per level. They do not store, so you cannot level twice and do two campaigns on the second level.

For maximum benefits, people will campaign level, meaning that they will complete a campaign, level, rinse, repeat. When you are doing this, however, you can run the risk of skipping a level's campaign by accidentally leveling. So, that's where automatic noexp comes in.

The way it works is this:

Say you take a campaign at level 10. SnD recognizes that you have taken a campaign at level 10. During the course of the campaign, you level to level 11. SnD recognizes that you have NOT taken a campaign at level 11. Once SnD sees that you have reached the exp threshold, SnD activates noexp to prevent you from missing a campaign on the level. 

Does this help explain it?
