### ISSUE TITLE
SnD breaks down when trying to list shop item

### ISSUE THREAD

**Issue by mtrp12** [AardCrowley/Search-and-Destroy#75]
SND malfunctions.
![image](https://user-images.githubusercontent.com/6695345/126809452-d5e99be2-26f9-42bf-8bfa-047f701ab2cc.png)

Steps to reproduce:
1. Go to boot camp HQ shop, military surplus store
2. Do "xset index areas"
3. type list

**Comment by mtrp12** [comment]
snd reload does fix it...until the next reproduction.

**Comment by AardCrowley** [comment]
Hmm, did you wait for the xset index areas to complete? I cannot reproduce this, but it may be related to the Pint of Sangria item in the shop, which is no longer there. If you can find another pint of sangria somewhere, and try to reproduce it, that would be great. We'll check if there's something on our end, though. Thank you for reporting this!

**Comment by mtrp12** [comment]
im not sure how long i should wait for it to finish. most of the time it just stops at next/last/first/quit/.... paging line, no success msg afterwards. so, i just continue with my thing after a bit. as for pint of sangria, im still new, i dont have much idea about it. i will try.

**Comment by mtrp12** [comment]
i have kept a seal of approval for you

![image](https://user-images.githubusercontent.com/6695345/126847030-2f8202a8-632f-4855-bbe4-cc44f4964e99.png)

**Comment by AardCrowley** [comment]
Problem is related to paging not turning it off - see issue #76
