### ISSUE TITLE
New Epic area

### ISSUE THREAD

**Issue by mtrp12** [AardCrowley/Search-and-Destroy#86]
New epic area added and breaking SnD
![image](https://user-images.githubusercontent.com/6695345/129508311-0e0306f5-50d1-41a4-b17e-e12f00a58e89.png)

![image](https://user-images.githubusercontent.com/6695345/129508341-63daed7f-195d-4eeb-a188-fb6ffe166169.png)

**Comment by AardCrowley** [comment]
Use the 'xset index areas' command. Need to do that when new areas are
added so it can be added to the SnD database. Otherwise, how would it know
one exists? I will look into a fix that doesn't present the error, though.

**Comment by mtrp12** [comment]
i did, this error is the output of xset index areas. for now i added the area to the lookup table in the plugin.
![image](https://user-images.githubusercontent.com/6695345/129737723-142a2c08-2f47-47d7-974e-ce0e5a8942dd.png)

**Comment by mtrp12** [comment]
It's failing in this line. Because there's no key named transcend in the table, the noquest is accessed on a nil object.
![image](https://user-images.githubusercontent.com/6695345/129738813-f057896b-d8cc-423b-a595-3d952bc11515.png)

**Comment by AardCrowley** [comment]
You're right. It is trying to index a nil value, so I'll need to change that to include an 'if' statement to check if it even exists. I'll fix that now. Whoops.

**Comment by AardCrowley** [comment]
This has been fixed in 5.91. Thank you.
