### ISSUE TITLE
Mobsearch breaks the search terms

### ISSUE THREAD

**Issue by mtrp12** [AardCrowley/Search-and-Destroy#87]
If I search for flying monkey using the command `ms "flying monkey"` it ignores the quotation. How should i search for multiword mobs?Is this feature available? If not requesting feature to search with multiple word. If I search with monkey or flying only, it does return result. But then it returns many other flying mobs or other kind of monkeys too.
![image](https://user-images.githubusercontent.com/6695345/129519716-8cd69b6e-4dfe-438e-bd5e-2efe539b9298.png)

**Comment by AardCrowley** [comment]
ms all flying monkey
ms here flying monkey

Use those commands. At some point, I may make it more intuitive, though.
