### ISSUE TITLE
xset mark [room id]

### ISSUE THREAD

**Issue by AardPringle** [AardCrowley/Search-and-Destroy#96]
Let us manually set a room number as the start of the area it belongs to. Useful for triggers/aliases that disable non-golden chaos portals when joining a gquest.

**Comment by AardCrowley** [comment]
Almost an entire year later and I finally get around to addressing some of these issues.

xset mark [areaname] [id] now exists, but not officially released. You can use 'snd force update master' to update to the newest version with 'hot fixes' until an actual official version is released.

One added benefit is that you can now set your own keywords to areas, so you can do:

xset mark kimr 10866

to set a keyword of 'kimr' to go to room 10866. This could theoretically be done for 'mobs', too.
