### ISSUE TITLE
Northstar Broken

### ISSUE THREAD

**Issue by fudgewaffle** [AardCrowley/Search-and-Destroy#98]
Northstar xrt or clickable links for quests, runs to the location but wont enter the Tower of Orbs and I'm too dumb to know how to fix it for myself.

Currently runs to: sw2new3se2swn5e8s11e

Should run to: sw2new3se2swn5e8s11eu

Speedwalk is: 2s8e5ne2n39eu (But I assume it does the above because it's faster)

**Comment by AardCrowley** [comment]
It's either that you have your xset mark location in the wrong spot, or
something is preventing you from going up. Go to the room it should lead
you to and type 'xset mark' and see if that fixes it.

**Comment by fudgewaffle** [comment]
That was the first thing I did and it still didn't work.

**Comment by fudgewaffle** [comment]
And I don't have any aliases in-game or the client that would be overwriting the up

**Comment by AardCrowley** [comment]
When you type 'xrt northstar', what does it display at the start? In
particular, I'm looking for the room ID it is trying to run to:

X-runto: northstar, room ID: 11127 (default)

Also, what happens if you manually type 'mapper goto 11127'? Does it
complete the speedwalk then?

**Comment by fudgewaffle** [comment]
X-runto: northstar, room ID: 11127 (xset mark)

Going to: Tower of Orbs
run sw2new3se2swn5e8s11e
enter orb

Mapper shows the same, save for the first line:

Going to: Tower of Orbs
run sw2new3se2swn5e8s11e
enter orb

So I assume that means it's a mapper issue then? And if so would you know what to do to fix it? I appreciate your time and help very much either way!

**Comment by AardCrowley** [comment]
It is a mapper issue.

mapper showroom 2893
mapper thisroom

Check to see if there is a custom exit for 'enter orb' there. If there is,
you need to delete that custom exit. It sounds like you may have that
custom exit there erroneously. You probably meant to do 'mapper cexit enter
orb' in room 11127, but instead placed it in room 2893.

**Comment by fudgewaffle** [comment]
You sir, are a damned genius lol. I don't even know how I managed to set a cexit both in the tower and right outside but that was 100% the problem! Thank you again so much for your help on this, I'm sure you have much better things to do.

**Comment by AardCrowley** [comment]
I am glad that I was able to help! And "better things to do" is subjective,
like my boss thinks I have better things to do than sit here and reply, but
I have better things to do than do my actual work! Muahaha!

**Comment by fudgewaffle** [comment]
Lmao fair enough XD I'm right there with you, had to TeamViewer into my PC to do whatever you were asking rather than do my job XD
